import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64AnyAllKeys: Route = {
  title: "Any% All Keys",
  headerColor: titleColors.dk64,
  doc: "https://www.youtube.com/watch?v=Di0rg_X1FyU",
  steps: [
    `${dk64Colors.dk} Cranky, Barrel Barrel, wet escape, tag W1/W2`,
    `${dk64Colors.dk} Climb/moonkick toward Aztec, tag W2, Enter Aztec`,
    `${dk64Colors.dk} Phasewalk to skip llama cutscene`,
    `${dk64Colors.dk} Key 5, Key 2, RESET`,
    `${dk64Colors.header} ISG, Story Skip on, enter file`,
    `${dk64Colors.dk} Enter tag barrel, back to training grounds`,
    `${dk64Colors.dk} Vine Barrel, dry escape`,
    `${dk64Colors.dk} Pseudo-dive to swim to tag W1, Quit Game`,
    `${dk64Colors.header} EXAMINE FILE, Japes Boss, Quit`,
    `${dk64Colors.header} Castle Boss, get kicked out`,
    `${dk64Colors.header} Multiplayer, get kicked out`,
    `${dk64Colors.header} Caves Boss, get kicked out`,
    `${dk64Colors.header} Multiplayer, get kicked out`,
    `${dk64Colors.header} Galleon Boss, get kicked out`,
    `${dk64Colors.header} Multiplayer, get kicked out`,
    `${dk64Colors.header} Forest Boss, Quit`,
    `${dk64Colors.header} Factory Boss, Quit`,
    `${dk64Colors.header} Enter/exit Jetpac, get pulled in on main menu`,
    `${dk64Colors.dk} Leave Training Grounds, W1, Turn in Keys 5 & 2`,
    `${dk64Colors.dk} Cannon to Enter Castle`,
    `${dk64Colors.dk} Straight ahead/drop to T&S`,
    `${dk64Colors.tiny} Key 7 as Tiny, deathwarp, exit Castle, deathwarp, leave Castle lobby`,
    `${dk64Colors.tiny} Pseudo-dive to swim to Monkeyport`,
    `${dk64Colors.tiny} Helm Early, kickslide up slopes`,
    `${dk64Colors.dk} DK Helm, Key 8`,
    `${dk64Colors.dk} Double phasewalk to escape, deathwarp, leave Helm lobby`,
    `${dk64Colors.dk} Fall to Factory`,
    `${dk64Colors.dk} TAG W1, hatch skip, fall to T&S`,
    `${dk64Colors.tiny} Key 3, W1, exit Factory`,
    `${dk64Colors.dk} Leave Factory lobby, fall to Galleon`,
    `${dk64Colors.tiny} Tag at crossroads, cannon/vines to T&S, Key 4`,
    `${dk64Colors.tiny} Backflip over T&S, forward to void, exit Galleon`,
    `${dk64Colors.dk} Leave Galleon lobby, swim to K. Lumsy`,
    `${dk64Colors.dk} Turn in keys 8 & 3`,
    `${dk64Colors.dk} W1 to Japes GB [1], Enter Japes`,
    `${dk64Colors.dk} Bush Push, tree/vines to T&S, Key 1`,
    `${dk64Colors.dk} Plant Push to exit Japes`,
    `${dk64Colors.dk} W2 to Enter Caves`,
    `${dk64Colors.dk} Pseudo-dive, phaseswim to T&S by Snide`,
    `${dk64Colors.dk} Key 6, phasewalk to exit Caves`,
    `${dk64Colors.dk} Leave lobby, drop to K. Rool`,
    `${dk64Colors.header} K. Rool`
  ]
};
