import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64TANLE: Route = {
  title: "Tag Anywhere NLE",
  headerColor: titleColors.dk64,
  doc: "https://www.youtube.com/watch?v=xq_RB_XkilM",
  steps: [
    `${dk64Colors.header} Note: DK is fastest on land, Diddy is fastest underwater`,
    `${dk64Colors.header} Note: Flickerwalking is best done between Tiny and Chunky`,
    `${dk64Colors.header} Note: Shoot all Kasplats with Chunky`,
    `${dk64Colors.dk} Tag W4/W5/W1`,
    `${dk64Colors.lanky} Phaseswim to cage GB [1]`,
    `${dk64Colors.lanky} K. Lumsy, flickerwalk or phasewalk to Sprint GB [2]`,
    `${dk64Colors.dk} Void to main, Japes entry GB [3], enter Japes`,
    `${dk64Colors.header} *Japes`,
    `${dk64Colors.dk} Bush Push`,
    `${dk64Colors.diddy} Tag skew on DK cage GB [4]`,
    `${dk64Colors.dk} BP`,
    `${dk64Colors.tiny} BP`,
    `${dk64Colors.tiny} Skew to stump GB [5]`,
    `${dk64Colors.diddy} Skew to cage GB [6]`,
    `${dk64Colors.chunky} Skew to cage GB [7]`,
    `${dk64Colors.dk} Both DK GBs [9]`,
    `${dk64Colors.lanky} Skew to cage GB [10]`,
    `${dk64Colors.tiny} Drop, skew to cage GB [11]`,
    `${dk64Colors.lanky} Enter painting hill, clip to GB [12]`,
    `${dk64Colors.diddy} BP`,
    `${dk64Colors.lanky} BP, bonus GB [13]`,
    `${dk64Colors.diddy} Back to main, phaseswim underground`,
    `${dk64Colors.chunky} Flickerwalk or phasewalk to BP`,
    `${dk64Colors.tiny} Twirl across`,
    `${dk64Colors.chunky} Underground GP [14], deathwarp, rock GB [15]`,
    `${dk64Colors.dk} Blast course GB [16]`,
    `${dk64Colors.dk} Phasefall/phasewalk on wall behind to enter T&S`,
    `${dk64Colors.diddy} Key 1, tunnel GB [17]`,
    `${dk64Colors.lanky} Bonus GB (use DK) [18] exit Japes`,
    `${dk64Colors.header} *Isles to Aztec`,
    `${dk64Colors.chunky} Move rock`,
    `${dk64Colors.lanky} Trombone GB [19], leave lobby`,
    `${dk64Colors.dk} Turn in Key 1, tag W2/W3, enter Aztec`,
    `${dk64Colors.header} *Aztec`,
    `${dk64Colors.dk} BP (can Twirl to it)`,
    `${dk64Colors.dk} To T&S, Key 2`,
    `${dk64Colors.diddy} BP, drop to enter Tiny Temple`,
    `${dk64Colors.diddy} Ledge clip to free Tiny GB [20]`,
    `${dk64Colors.tiny} Phaseswim to spawn snag Klaptrap GB [21]`,
    `${dk64Colors.chunky} Phaseswim to Klaptrap GB [22]`,
    `${dk64Colors.dk} Tag skew to leave temple, Guitar Skip`,
    `${dk64Colors.tiny} BP, face clip, enter Llama Temple from underneath`,
    `${dk64Colors.dk} Phaseswim/tag skew, free Lanky GB [23]`,
    `${dk64Colors.lanky} Skew to matching game GB [24]`,
    `${dk64Colors.lanky} Skew to BP`,
    `${dk64Colors.tiny} Lava GB [25], exit Aztec`,
    `${dk64Colors.header} *Isles to Factory`,
    `${dk64Colors.dk} Leave Lobby, turn in Key 2`,
    `${dk64Colors.tiny} Monkeyport to Saxophone GB [26]`,
    `${dk64Colors.chunky} Drop to Factory Lobby, punch box`,
    `${dk64Colors.tiny} BP`,
    `${dk64Colors.dk} Tag midair for Bongos GB [27], enter Factory`,
    `${dk64Colors.dk} Hatch skip, OOB to open Tiny cage`,
    `${dk64Colors.lanky} Pipe GB [28], tag W4, drop`,
    `${dk64Colors.lanky} Free Chunky GB [29]`,
    `${dk64Colors.tiny} BP, climb to T&S`,
    `${dk64Colors.tiny} Key 3, cage GB [30]`,
    `${dk64Colors.chunky} Flickerwalk or phasewalk to BP`,
    `${dk64Colors.lanky} To R&D, BP`,
    `${dk64Colors.dk} Fall to activate power shed GB [31]`,
    `${dk64Colors.chunky} Dark room GB [32], slam Prod switch`,
    `${dk64Colors.diddy} Slam Prod switch, BP`,
    `${dk64Colors.chunky} W4 to crusher GB [33]`,
    `${dk64Colors.diddy} Climb to Spring GB [34]`,
    `${dk64Colors.dk} BP, drop to crusher room GB [35], exit Factory`,
    `${dk64Colors.header} *Isles to Galleon`,
    `${dk64Colors.diddy} Leave Lobby, drop to Snide bonus GB [36]`,
    `${dk64Colors.diddy} Turn in BPs x3 [39]`,
    `${dk64Colors.dk} Turn in BPs x3 [42]`,
    `${dk64Colors.dk} Drop to cage GB [43]`,
    `${dk64Colors.chunky} Galleon Lobby BP, enter Galleon`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.chunky} Flickerwalk or phasewalk to spawn snag cannon game GB [44]`,
    `${dk64Colors.lanky} BP, phaseswim to lighthouse, Enguarde GB [45]`,
    `${dk64Colors.diddy} BP, exit/enter`,
    `${dk64Colors.chunky} Chest GB [46]`,
    `${dk64Colors.tiny} Vines to BP, enter T&S, Key 4`,
    `${dk64Colors.chunky} Flickerwalk or phasewalk to BP`,
    `${dk64Colors.lanky} Phaseswim to 5DS GB [47]`,
    `${dk64Colors.tiny} Phaseswim to 5DS GB [48], exit Galleon`,
    `${dk64Colors.header} *Isles to Forest`,
    `${dk64Colors.tiny} Phaseswim to pipe GB [49], leave Lobby`,
    `${dk64Colors.tiny} STS to cage GB [50], W5, W1, turn in Key 4`,
    `${dk64Colors.chunky} W1, W5, slam X, STS to cage GB [51], rock GB [52]`,
    `${dk64Colors.chunky} Cannon, enter Forest`,
    `${dk64Colors.header} *Forest`,
    `${dk64Colors.dk} Pink tunnel, enter mushroom`,
    `${dk64Colors.header} Shoot all switches except DK's`,
    `${dk64Colors.dk} Shoot switch/slam cancel cutscene, cannon to GB [53]`,
    `${dk64Colors.lanky} Leave mushroom top, slam switch, dark room GB [54]`,
    `${dk64Colors.chunky} Drop to BP`,
    `${dk64Colors.tiny} Twirl to middle mushroom entrance`,
    `${dk64Colors.diddy} BP, leave middle mushroom`,
    `${dk64Colors.tiny} Drop to BP`,
    `${dk64Colors.lanky} Phaseswim/tag skew to owl area, BP`,
    `${dk64Colors.tiny} Skew into stump, Klaptrap GB [55]`,
    `${dk64Colors.tiny} Deathwarp or exit/enter`,
    `${dk64Colors.dk} Blue tunnel to Snide T&S, DDQ Key 5`,
    `${dk64Colors.tiny} Turn in BPs x6 [61]`,
    `${dk64Colors.dk} Enter mill, clip for GB [62], leave mill`,
    `${dk64Colors.diddy} Phaseswim to cage GB [63]`,
    `${dk64Colors.dk} Phaseswim/damage skew to BP, exit Forest`,
    `${dk64Colors.header} *Isles to Caves`,
    `${dk64Colors.diddy} Cage GB [64], drop to W3, W1`,
    `${dk64Colors.dk} Turn in Key 5, W1, W2`,
    `${dk64Colors.chunky} Move rock for Triangle GB [65]`,
    `${dk64Colors.chunky} Enter Caves Lobby, punch left wall`,
    `${dk64Colors.lanky} BP`,
    `${dk64Colors.diddy} Guitar GB [66] enter Caves`,
    `${dk64Colors.header} *Caves`,
    `${dk64Colors.dk} Tag W2, climb to BP`,
    `${dk64Colors.chunky} Drop left, punch Snide wall, enter T&S`,
    `${dk64Colors.dk} Key 6`,
    `${dk64Colors.chunky} Phaseswim/tag skew to Gone GB [67]`,
    `${dk64Colors.tiny} Twirl across river`,
    `${dk64Colors.diddy} Rocket to W5`,
    `${dk64Colors.lanky} BP`,
    `${dk64Colors.diddy} Skew to BP`,
    `${dk64Colors.tiny} Monkeyport to GB [68], Twirl to tag, igloo, W1, Chunky GB`,
    `${dk64Colors.chunky} Get GB [69]`,
    `${dk64Colors.tiny} Twirl to skew in Tiny 5DI GB [70]`,
    `${dk64Colors.chunky} BP`,
    `${dk64Colors.dk} Phaseswim to DK 5DI GB [71], deathwarp`,
    `${dk64Colors.lanky} Phaseswim to Lanky 5DI GB [72], exit Caves`,
    `${dk64Colors.chunky} Drop left, punch wall`,
    `${dk64Colors.dk} Damage boost to lava GB [73], deathwarp, leave Lobby`,
    `${dk64Colors.dk} Drop to warps, W4, drop to Snide`,
    `${dk64Colors.lanky} Turn in BPs x7 [80]`,
    `${dk64Colors.dk} Leave, drop to cannon, Castle Lobby, shoot switch`,
    `${dk64Colors.diddy} BP, enter Castle`,
    `${dk64Colors.header} *Castle`,
    `${dk64Colors.dk} Flickerwalk or phasewalk in tree, BP`,
    `${dk64Colors.dk} OOB to tree GB [81], leave`,
    `${dk64Colors.diddy} Climb left to warps`,
    `${dk64Colors.dk} Drop to tunnel by water`,
    `${dk64Colors.chunky} BP, leave the way you came in`,
    `${dk64Colors.diddy} Phaseswim right of tunnel door to airswim to crypt`,
    `${dk64Colors.diddy} BP, leave`,
    `${dk64Colors.tiny} BP, climb x1`,
    `${dk64Colors.diddy} Left to Rocketbarrel, rocket to Snide, turn in BPs x5 [86]`,
    `${dk64Colors.tiny} Turn in BPs x1 [87]`,
    `${dk64Colors.chunky} Turn in BPs x7 [94]`,
    `${dk64Colors.dk} Turn in BPs x3 [97]`,
    `${dk64Colors.dk} Library clip for GB/door open overlap [98]`,
    `${dk64Colors.dk} Drop right, enter trash can`,
    `${dk64Colors.tiny} Trash GB [99]`,
    `${dk64Colors.chunky} Shed GB [100]`,
    `${dk64Colors.lanky} Enter T&S, Key 7, exit Castle`,
    `${dk64Colors.header} *Isles to Helm`,
    `${dk64Colors.dk} Deathwarp, leave Lobby, turn in Keys 7, 3, 6`,
    `${dk64Colors.tiny} Monkeyport to Helm Lobby`,
    `${dk64Colors.chunky} Enter Helm`,
    `${dk64Colors.header} *Helm`,
    `${dk64Colors.tiny} Climb slopes`,
    `${dk64Colors.dk} DK or Chunky Helm`,
    `${dk64Colors.dk} Key 8, Quit Game`,
    `${dk64Colors.header} *Isles to K. Rool`,
    `${dk64Colors.dk} W1, turn in Key 8 RESET`,
    `${dk64Colors.dk} W1, W3`,
    `${dk64Colors.header} *K. Rool`
  ]
};
