import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64TA101: Route = {
  title: "Tag Anywhere 101%",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1-YAMaJ9dKtKzEmVvWUWtHMX2m7yJ4qiOu-mw4gigMSg",
  steps: [
    `${dk64Colors.header} *Start to Fungi`,
    `${dk64Colors.dk} Tag Ring W4. To rocks by Caves`,
    `${dk64Colors.chunky} Instrument [1]`,
    `${dk64Colors.lanky} Instrument for Rocketbarrel, Tag W2`,
    `${dk64Colors.dk} Fungi Early`,
    `${dk64Colors.diddy} Caged GB [2]`,
    `${dk64Colors.tiny} Lobby Fairy`,
    `${dk64Colors.dk} Enter Fungi`,
    `${dk64Colors.header} *Fungi - Earliest Possible Rabbit Race`,
    `${dk64Colors.chunky} Tag W2 (5)`,
    `${dk64Colors.lanky} Tag W1 (5)`,
    `${dk64Colors.diddy} Rocketbarrel to clock turn to night (10).`,
    `${dk64Colors.tiny} Tag W4, tag W3 (5)`,
    `${dk64Colors.dk} Red Tunnel CBs (5). Low W5 bunch (10).`,
    `${dk64Colors.lanky} Rabbit Race Skip [3]`,
    `${dk64Colors.header} Snag Instructions: Orangstand right until splash.`,
    `${dk64Colors.header} Keep holding B, Hold Down-Left for 6 Beats.`,
    `${dk64Colors.header} Left for 8 Beats.`,
    `${dk64Colors.header} Down-left for 22 Beats.`,
    `${dk64Colors.header} Left for 12 Beats.`,
    `${dk64Colors.header} Tap left and jump out of fake water. Hold Down for 22 beats.`,
    `${dk64Colors.lanky} Tag after getting GB.`,
    `${dk64Colors.lanky} Bunch and 1 CB near Rabbit (11).`,
    `${dk64Colors.diddy} 2 CBs to Lanky Kasplat (12).`,
    `${dk64Colors.tiny} Anthill (13) with Bean and GB [4]. Cannon out.`,
    `${dk64Colors.diddy} Summon Owl.`,
    `${dk64Colors.lanky} Blueprint.`,
    `${dk64Colors.diddy} 3 CBs to Rocketbarrel (15). Owl Race. Busy Barrel Barrage (20) [5].`,
    `${dk64Colors.diddy} Take W4 (30).`,
    `${dk64Colors.chunky} Well (10) [6].`,
    `${dk64Colors.tiny} Swim Clockwise for 7 (12). Phase Swim under Mill.`,
    `${dk64Colors.diddy} Tag Anywhere Skew for Underwater Caged [7]. Backflip inbounds.`,
    `${dk64Colors.tiny} Skew into Tiny entrance (17)`,
    `${dk64Colors.chunky} Start Crusher (15)`,
    `${dk64Colors.tiny} Spider [8] and back mill CBs (32)`,
    `${dk64Colors.chunky} OOB to front of mill. Mill GB [9]. Crusher GB [10]. Flicker Walk OOB near Lanky Coins.`,
    `${dk64Colors.dk} Balloon (10). Leave Mill.`,
    `${dk64Colors.lanky} Balloon to Attic (21). Collect Homing Ammo, shoot bats, get Bunch (26) [11].`,
    `${dk64Colors.dk} Moonkick to mushroom by Blue Tunnel.`,
    `${dk64Colors.diddy} Snipe Snide's balloon (25).`,
    `${dk64Colors.dk} Balloon behind Diddy barn (20)`,
    `${dk64Colors.diddy} Diddy attic (43) [12] and Fairy. Leave Diddy Attic.`,
    `${dk64Colors.tiny} Swim to thorn bushes for 5 (37). Phase Swim and Skew on thorn bushes.`,
    `${dk64Colors.tiny} Balloon (47). Inbounds near Funky.`,
    `${dk64Colors.chunky} Tag W2 (20). Hunky Chunky for Apple and CBs (29) [13]. Skew through blue wall.`,
    `${dk64Colors.dk} Blueprint. Bunch over switch (25). Enter DK Barn. Minecart Mayhem and Fairy (30) [14].`,
    `${dk64Colors.header} Fungi Minecart Mayhem:`,
    `${dk64Colors.header} 3-2-1-1-4-2-go back to inside track`,
    `${dk64Colors.dk} Exit/Enter on Fairy.`,
    `${dk64Colors.dk} Red Tunnel (35)`,
    `${dk64Colors.lanky} Tag W3 and 4 CBs around right (35)`,
    `${dk64Colors.diddy} Rocketbarrel to Teetering Turtle Trouble (53) [15]`,
    `${dk64Colors.lanky} Switch (40), Dark Room (bottom right lanky face) (50) [16], Light Room (upper left lanky face) (55) [17]`,
    `${dk64Colors.diddy} CBs to Crown (56). Crown. Climb back up. CBs to Chunky Room (58).`,
    `${dk64Colors.chunky} Face Puzzle and balloon (44) [18]`,
    `${dk64Colors.diddy} CBs to above Chunky Kasplat (60)`,
    `${dk64Colors.chunky} Blueprint and balloon (54). Enter Mush (59). Drop left.`,
    `${dk64Colors.diddy} Blueprint.`,
    `${dk64Colors.chunky} Drop for CBs (75)`,
    `${dk64Colors.chunky} Shoot Switch.`,
    `${dk64Colors.dk} Shoot Switch.`,
    `${dk64Colors.diddy} Shoot Switch.`,
    `${dk64Colors.lanky} Shoot Switch and Balloon (65)`,
    `${dk64Colors.tiny} Shoot Switch and Slam Switch Overlap (52) and Speedy Swing Sortie [19].`,
    `${dk64Colors.dk} Slam Switch and take Cannons to GB (50) [20]`,
    `${dk64Colors.lanky} Balloon (75)`,
    `${dk64Colors.dk} Leave Mush. W5 bunch (55). Drop left of W5 to Bblast [21] GET 2 COINS (65). CBs around left to Tiny Kasplat (75)`,
    `${dk64Colors.tiny} Blueprint and balloon (62). Tag Anywhere Skew and go through the wall by Tag Barrel to Beanstalk. Mini Monkey and grow the Beanstalk for GB [22]. Pause Exit.`,
    `${dk64Colors.header} *Fungi to Helm`,
    `${dk64Colors.tiny} Flour Push.`,
    `${dk64Colors.chunky} Gorilla Gone For Crown. Leave Lobby.`,
    `${dk64Colors.diddy} Summit Peril Path Panic [23]. Diddy “Helm Early”.`,
    `${dk64Colors.tiny} Fairy and Instrument Pad [24]. Helm Early. Homing Ammo.`,
    `${dk64Colors.chunky} Gorilla Gone Kremling Kosh [25]. Deathwarp.`,
    `${dk64Colors.diddy} Homing Ammo. Enter Helm.`,
    `${dk64Colors.header} *Hideout Helm`,
    `${dk64Colors.tiny} Slope climb.`,
    `${dk64Colors.chunky} Switch and T1 to DK Room.`,
    `${dk64Colors.dk} Barrels and Instrument when Barrel Explodes. Medal.`,
    `${dk64Colors.dk} Crystal Push out to the main area. Pull Lever. Around left to Rocketbarrel.`,
    `${dk64Colors.diddy} Rocketbarrel through the stars.`,
    `${dk64Colors.chunky} Chunky Room Barrels and Medal.`,
    `${dk64Colors.tiny} Tiny Room Barrels and Medal.`,
    `${dk64Colors.lanky} Lanky Room Barrels and Medal. DO BOTTOM FIRST.`,
    `${dk64Colors.diddy} Rocketbarrel to Diddy Room for Barrels and Medal. DO LEFT FIRST.`,
    `${dk64Colors.diddy} Rocketbarrel to Crown.`,
    `${dk64Colors.tiny} PTT Forward.`,
    `${dk64Colors.dk} Key 8 and Fairies. Pause Exit.`,
    `${dk64Colors.header} *Helm to Factory`,
    `${dk64Colors.dk} Blueprint. Deathwarp and drop down.`,
    `${dk64Colors.chunky} Box.`,
    `${dk64Colors.tiny} Blueprint and Fairy.`,
    `${dk64Colors.dk} Instrument [26]. Enter Factory.`,
    `${dk64Colors.header} *Factory`,
    `${dk64Colors.chunky} W1 bunch (5)`,
    `${dk64Colors.lanky} Hatch skip, lower gate from underneath, Pipe GB and CBs (25) [27]`,
    `${dk64Colors.dk} Blueprint, tag High W4`,
    `${dk64Colors.chunky} 1 bunch on arm (10)`,
    `${dk64Colors.dk} Bblast (20)`,
    `${dk64Colors.lanky} Free Chunky GB [28]`,
    `${dk64Colors.chunky} Dark room (25) [29], W1 bunch (30)`,
    `${dk64Colors.tiny} Blueprint`,
    `${dk64Colors.chunky} Stash Snatch [30]`,
    `${dk64Colors.tiny} Key 3, bookshelf (5) and caged GB [31]. Exit/Enter.`,
    `${dk64Colors.lanky} W2 bunch (30)`,
    `${dk64Colors.chunky} Phase Walk/Fall to Snide's`,
    `${dk64Colors.tiny} Balloon (15)`,
    `${dk64Colors.chunky} W3 bunch and balloon (45)`,
    `${dk64Colors.dk} Number Game and balloon (35) [32] and fairy`,
    `${dk64Colors.lanky} Batty Barrel Bandit [33]`,
    `${dk64Colors.tiny} Dartboard (25) [34], Tag Funky W5`,
    `${dk64Colors.dk} Round 1 skip and Nintendo Coin [35]`,
    `${dk64Colors.diddy} W5 back (10)`,
    `${dk64Colors.tiny} Fairy, balloon (35)`,
    `${dk64Colors.chunky} Blueprint`,
    `${dk64Colors.diddy} Block tower (30) [36]`,
    `${dk64Colors.lanky} Piano Game Spawn Snag (18-20 Lanky noises down-left, backflip left twice) and balloon (40) [37], Great Escape or SLCC, to diddy room (44)`,
    `${dk64Colors.diddy} 3124, 4231, 3 balloons, 1342 (60) [38]`,
    `${dk64Colors.lanky} Blueprint and tag w2 (55)`,
    `${dk64Colors.tiny} Car race (45) [39], phase walk or Exit/Enter W2 back`,
    `${dk64Colors.chunky} Phase walk/fall to Crown, Chunky room (65) [40]`,
    `${dk64Colors.dk} Balloon above drop (45), Power Shed (60) [41]`,
    `${dk64Colors.diddy} Beaver bother [42]`,
    `${dk64Colors.chunky} Production Switch`,
    `${dk64Colors.diddy} Production Switch, Blueprint`,
    `${dk64Colors.tiny} W4, tiny balloon (55)`,
    `${dk64Colors.chunky} Crusher GB and 2 bunches (75) [43]`,
    `${dk64Colors.tiny} Conveyors (75) and Krazy Kong Klamour [44]`,
    `${dk64Colors.lanky} Upper Production Balloon (65)`,
    `${dk64Colors.diddy} Cylinders and GB (75) [45]`,
    `${dk64Colors.dk} Crusher Room (75) [46]`,
    `${dk64Colors.lanky} Crusher Balloon (75), Pause Exit`,
    `${dk64Colors.header} *Factory to Aztec`,
    `${dk64Colors.dk} W4 down. W2 up. Aztec Early. Enter Aztec.`,
    `${dk64Colors.header} *Aztec`,
    `${dk64Colors.chunky} Chunky Vase GB (20) [47]`,
    `${dk64Colors.dk} DK Kasplat {1}.`,
    `${dk64Colors.lanky} 2 CBs to Oasis (2).`,
    `${dk64Colors.dk} Tag W1. Moonkick to Diddy Kasplat.`,
    `${dk64Colors.diddy} Diddy Blueprint {1}. Enter Tiny Temple.`,
    `${dk64Colors.diddy} Free Tiny GB [48].`,
    `${dk64Colors.tiny} Balloons (20).`,
    `${dk64Colors.diddy} Underwater CBs (4).`,
    `${dk64Colors.lanky} Underwater CBs (6). Bunch on Vulture Switch (11).`,
    `${dk64Colors.chunky} Balloon (30). Vulture Twice.`,
    `${dk64Colors.lanky} GB [49], Crown, and CBs (16)`,
    `${dk64Colors.tiny} Spawn Snag Klaptraps GB [50] (25)`,
    `${dk64Colors.chunky} STVW for Klaptraps GB [51]. Chunky CBs in corner (55).`,
    `${dk64Colors.diddy} Exit Temple. Balloon and Bunch (19).`,
    `${dk64Colors.dk} Guitar Skip`,
    `${dk64Colors.diddy} Hallway CBs (24).`,
    `${dk64Colors.tiny} Blueprint {1}.`,
    `${dk64Colors.lanky} 1 CB on Snake Road. (17)`,
    `${dk64Colors.dk} Balloons (20)`,
    `${dk64Colors.chunky} Hunky Chunky Clip into Busy Barrel Barrage [52].`,
    `${dk64Colors.tiny} CBs to Rocketbarrel Platform (30)`,
    `${dk64Colors.diddy} CBs on Rocketbarrel Stairs (27). Free Vulture (32) and ram gongs. Bunch on Llama Temple (37). Vulture GB [53]. CBs on Trees around tower and gongs GB [54] (52). Singles down ramp (55).`,
    `${dk64Colors.tiny} Mini Monkey (35) and Beetle Race [55]. Climb tree near Rocketbarrel platform.`,
    `${dk64Colors.lanky} Bunch on Tree (22). Jump to Rocketbarrel Platform.`,
    `${dk64Colors.dk} Bblast. CBs on Ramp (24). Balloon behind Llama Temple (34). Enter Llama Temple.`,
    `${dk64Colors.dk} Moonkick into Bonus, fall into water. Skew in Lanky Room.`,
    `${dk64Colors.lanky} Balloons (42).`,
    `${dk64Colors.dk} Free Lanky GB [56]. Inbounds by stairs. 3 CBs on stairs (37). Climb to Matching Game.`,
    `${dk64Colors.lanky} Matching Game [57].`,
    `${dk64Colors.tiny} Skew through wall to Lava room. Bunch (40), GB [58], Bunch (45).`,
    `${dk64Colors.lanky} Blueprint {1}`,
    `${dk64Colors.tiny} Skew through bottle (50). Fairy.`,
    `${dk64Colors.dk} Moonkick to Bonus GB`,
    `${dk64Colors.lanky} Midair Tag for Bonus GB [59].`,
    `${dk64Colors.tiny} Balloon above Lava (60).`,
    `${dk64Colors.lanky} W1 bunch (47) and CBs leaving (50). 3 Trees to Funky (65).`,
    `${dk64Colors.dk} Keys 5 and 2. Banana Push to Stealthy Snoop [60].`,
    `${dk64Colors.diddy} Balloon (65).`,
    `${dk64Colors.dk} Leave Tunnel (57)`,
    `${dk64Colors.tiny} CBs on path to 5DT (65).`,
    `${dk64Colors.dk} 5DT [61]`,
    `${dk64Colors.diddy} 5DT and Balloon [62] (75)`,
    `${dk64Colors.tiny} Bunches on front trees (75). Tiny 5DT with Fairy [63].`,
    `${dk64Colors.lanky} 5DT and Balloon [64] (75)`,
    `${dk64Colors.chunky} 5DT with both Balloon and Blueprint {1} [65] (75). Exit/Enter.`,
    `${dk64Colors.dk} W1. Trees (72), CBs to Llama Cage (75) and Free Llama GB [66]. Pause Exit.`,
    `${dk64Colors.header} *Aztec Lobby`,
    `${dk64Colors.diddy} Charge the Gongs.`,
    `${dk64Colors.tiny} PTT to Bonus [67]. Save and Quit Game.`,
    `${dk64Colors.header} *Aztec to Galleon`,
    `${dk64Colors.header} Re-enter file`,
    `${dk64Colors.dk} W4 up. Fall to Snide's area.`,
    `${dk64Colors.chunky} Battle Crown.`,
    `${dk64Colors.diddy} Batty Barrel Bandit [68]`,
    `${dk64Colors.dk} Back out to Isles. Caged GB [69]. Enter Galleon Lobby.`,
    `${dk64Colors.chunky} Blueprint. Enter Galleon.`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.lanky} Hallway CBs (5).`,
    `${dk64Colors.chunky} Hallway and W2 (7). Chests GB [70] (12).`,
    `${dk64Colors.dk} Balloon (10) and Fairy.`,
    `${dk64Colors.tiny} Blueprint {5} (8)`,
    `${dk64Colors.chunky} To T&S (15). Key 4. Punch Crown Gate.`,
    `${dk64Colors.lanky} Crown and Balloons (25).`,
    `${dk64Colors.diddy} Cannon to Cranky (10). Rareware Coin. Flicker Walk to Tag W5. Cactus Balloon (20).`,
    `${dk64Colors.chunky} Blueprint {5} and Balloon (25).`,
    `${dk64Colors.lanky} Bunch on Cactus (30).`,
    `${dk64Colors.tiny} Submarine GB [71]. Exit/Enter.`,
    `${dk64Colors.chunky} Flicker Walk to Spawn Snag Cannon Game GB [72].`,
    `${dk64Colors.lanky} Blueprint {4}.`,
    `${dk64Colors.tiny} Bunches (23).`,
    `${dk64Colors.chunky} Balloon (35). Phase Swim to 2DS.`,
    `${dk64Colors.lanky} 2DS [73] (40).`,
    `${dk64Colors.tiny} 2DS [74] (33).`,
    `${dk64Colors.lanky} Balloon above 5DS (50). Bunch under Enguarde (55).`,
    `${dk64Colors.chunky} 5DS [75].`,
    `${dk64Colors.diddy} 5DS [76] (25). Skip bunch on right.`,
    `${dk64Colors.lanky} 5DS [77] (70).`,
    `${dk64Colors.dk} Underwater Bunches (25).`,
    `${dk64Colors.chunky} Underwater Bunches (50).`,
    `${dk64Colors.tiny} 5DS and Fairy [78] (48).`,
    `${dk64Colors.dk} 5DS [79] (30).`,
    `${dk64Colors.diddy} Swim to Treasure Room (30).`,
    `${dk64Colors.tiny} Bunch and Balloon (63).`,
    `${dk64Colors.diddy} Balloon (40).`,
    `${dk64Colors.dk} Blueprint {7}`,
    `${dk64Colors.diddy} Bonus [80].`,
    `${dk64Colors.tiny} PTT across to Lanky Gold Tower.`,
    `${dk64Colors.lanky} Gold Tower [81] (75). Pearls. Exit/Enter.`,
    `${dk64Colors.tiny} 2 CBs to Lighthouse (65).`,
    `${dk64Colors.dk} Open Gate or Phasewalk OOB.`,
    `${dk64Colors.lanky} Enguarde GB [82].`,
    `${dk64Colors.tiny} Mermaid GB [83]. Leave Mermaid.`,
    `${dk64Colors.diddy} Swim up to Blueprint {4}.`,
    `${dk64Colors.tiny} Balloon (75).`,
    `${dk64Colors.dk} Raise Water Level. Balloon (40). Bblast with 3 bunches (55).`,
    `${dk64Colors.diddy} Seal Balloon from Bblast pad (50).`,
    `${dk64Colors.dk} Lighthouse GB [84] (75). Kick to Ship.`,
    `${dk64Colors.diddy} Slam Switch with Diddy.`,
    `${dk64Colors.chunky} Seasick GB [85] (75) - Punch 2 Barrels`,
    `${dk64Colors.diddy} Summon Mech Fish and get Ship Switch GB [86].`,
    `${dk64Colors.diddy} Top of Lighthouse (60). STVW to 5DS Area. Enter Mech Fish. Use Oranges for Fast Shot [87].`,
    `${dk64Colors.diddy} Bunches at bottom (75). Swim up to Seal.`,
    `${dk64Colors.dk} Seal GB [88].`,
    `${dk64Colors.diddy} Seal Race GB [89]. Pause Exit x2.`,
    `${dk64Colors.header} *Galleon to Castle`,
    `${dk64Colors.tiny} Lobby GB [90]. Void.`,
    `${dk64Colors.lanky} Leave Lobby. K. Lumsy Caged [91]. Orangstand GB [92]. Turn Keys 8, 2, 3, 4, 5. Enter Castle Lobby. Searchlight Seek Bonus [93].`,
    `${dk64Colors.diddy} Blueprint.`,
    `${dk64Colors.dk} Enter Castle.`,
    `${dk64Colors.header} *Castle`,
    `${dk64Colors.dk} Bridge (5)`,
    `${dk64Colors.tiny} PTT to Low Rocketbarrel`,
    `${dk64Colors.diddy} Rocketbarrel to Tower [94].`,
    `${dk64Colors.lanky} Lanky Tower (10) [95].`,
    `${dk64Colors.tiny} Fall left and walk up (11).`,
    `${dk64Colors.dk} Library Clip (10) [96]`,
    `${dk64Colors.tiny} Walk right and fall to trash (15), Trash Can (20) [97]`,
    `${dk64Colors.lanky} Greenhouse and Crown (40) [98]`,
    `${dk64Colors.chunky} Shed (10) [99]. Tag W4. Key 7.`,
    `${dk64Colors.diddy} Ballroom (25) [100]. Normal Speed 1 1 1 1 3 2 3 1`,
    `${dk64Colors.tiny} Monkeyport bunches, Car Race, Fairy, balloon (50) [101].`,
    `${dk64Colors.chunky} Phase Walk/Fall to Museum GB and balloon (20) [102]. Exit/Enter. Tree jump to take W4.`,
    `${dk64Colors.lanky} Drop to Blueprint.`,
    `${dk64Colors.dk} To W2 (15).`,
    `${dk64Colors.tiny} To Cranky (60).`,
    `${dk64Colors.dk} Drop right and grab CB at top of pole and on pole (17).`,
    `${dk64Colors.tiny} Blueprint.`,
    `${dk64Colors.dk} Climb and walk around to Tree (40).`,
    `${dk64Colors.tiny} Flicker Walk into Tree.`,
    `${dk64Colors.chunky} Bunch, balloon, and Beaver Bother (35) [103].`,
    `${dk64Colors.dk} Blueprint, balloon, Fairy, GB, and bunch (55) [104].`,
    `${dk64Colors.chunky} Swim to Dungeon. Dungeon (55). Enter Basement. Basement balloons (75).`,
    `${dk64Colors.diddy} Diddy Basement (35) [105]. DO NOT TAG OR YOU WILL GET STUCK. Bunches by DK room (45).`,
    `${dk64Colors.dk} DK Basement (60) [106].`,
    `${dk64Colors.diddy} Bunches by Lanky Room (55).`,
    `${dk64Colors.lanky} Lanky Basement with far balloon only (50) [107]. Deathwarp back. Leave Basement.`,
    `${dk64Colors.tiny} Tiny Dungeon Teetering Turtle Trouble [108].`,
    `${dk64Colors.lanky} Lanky bunch and enter Crypt (55). Lanky Crypt (65) [109].`,
    `${dk64Colors.tiny} Tiny Crypt (65) [110].`,
    `${dk64Colors.lanky} Lanky bunches to Funky (75).`,
    `${dk64Colors.tiny} Funky balloon (75).`,
    `${dk64Colors.diddy} Blueprint. Balloon outside Diddy Crypt switch (65). Tag main W1.`,
    `${dk64Colors.diddy} Diddy Crypt and balloon in coffin (75) [111]. W1 back. Tag W3.`,
    `${dk64Colors.chunky} Chunky Crypt [112]. W3 back/phasewalk/fall to DK room.`,
    `${dk64Colors.dk} DK Crypt bunch and balloon (75). Torch Clip/Phasewalk/Fall OOB and enter Minecart`,
    `${dk64Colors.dk} OR Top left, top right, bottom left for Minecart.`,
    `${dk64Colors.dk} Reset on Minecart GB [113]`,
    `${dk64Colors.header} *Castle to Caves`,
    `${dk64Colors.header} Re-enter File`,
    `${dk64Colors.dk} W2 go to Caves.`,
    `${dk64Colors.lanky} Blueprint.`,
    `${dk64Colors.diddy} Instrument [114]`,
    `${dk64Colors.lanky} Enter Caves.`,
    `${dk64Colors.header} *Caves`,
    `${dk64Colors.lanky} CBs (5).`,
    `${dk64Colors.chunky} W2 bunch (5). All CBs near DK Kasplat (18)`,
    `${dk64Colors.dk} Blueprint`,
    `${dk64Colors.lanky} Ice Tomato (15) [115]. Beetle (20) [116]. Blueprint (40).`,
    `${dk64Colors.diddy} Rocketbarrel (1), MMM (6) [117], land on Lanky 1DC.`,
    `${dk64Colors.chunky} Key 6.`,
    `${dk64Colors.lanky} Pad on Lanky 1DC (45). 1DC (50) [118]. Waterfall Balloon (60).`,
    `${dk64Colors.dk} Rotating Room and Crown (5) [119]`,
    `${dk64Colors.chunky} W2 bunch (23)`,
    `${dk64Colors.tiny} Blueprint and Balloon (10).`,
    `${dk64Colors.chunky} 5DC (43) [120]`,
    `${dk64Colors.dk} 5DC [121]. Bunch Outside (10)`,
    `${dk64Colors.tiny} 5DC [122] (30).`,
    `${dk64Colors.diddy} Middle 5DC and 3 CBs (14) [123], Upper Balloon (24), Upper 5DC (39) [124], Exit/Enter`,
    `${dk64Colors.dk} W1 bunch (15).`,
    `${dk64Colors.diddy} Tag Anywhere Skew to Gorilla Gone room.`,
    `${dk64Colors.dk} Balloon (25).`,
    `${dk64Colors.chunky} Gorilla Gone GB and 2 singles (50) [125]`,
    `${dk64Colors.tiny} OOB Backflip to land near tag barrel. Cross river and climb to Funky.`,
    `${dk64Colors.diddy} Funky CBs (43). W4 Bunch (48). Blueprint and 2 CBs (50).`,
    `${dk64Colors.tiny} Balloon and Monkeyport (45) [126]. Tag W3 (50). Tag W1.`,
    `${dk64Colors.dk} W1 Bunch (30).`,
    `${dk64Colors.tiny} PTT to Chunky Ice Shield.`,
    `${dk64Colors.chunky} Ice Shield (55) [127]. WATCH OUT FOR THE AUTOSAVE ON THE GB`,
    `${dk64Colors.tiny} PTT to Tiny 5DI (65) [128].`,
    `${dk64Colors.chunky} Blueprint.`,
    `${dk64Colors.dk} DK 5DI bunch and balloon (50) [129]`,
    `${dk64Colors.diddy} Diddy 5DI (60) [130]`,
    `${dk64Colors.tiny} Swim to W4 (70)`,
    `${dk64Colors.diddy} W4 Bunch and Balloon (75)`,
    `${dk64Colors.dk} Bblast (70) [131] and CBs around (75).`,
    `${dk64Colors.tiny} Mini Monkey to Krazy Kong Klamour (75) [132].`,
    `${dk64Colors.chunky} Balloon (65). W3. STS into Chunky 5DI (75) [133].`,
    `${dk64Colors.lanky} STS into Lanky 5DI.`,
    `${dk64Colors.lanky} Lanky 5DI (75) [134]. Pause Exit.`,
    `${dk64Colors.header} *Caves to Japes`,
    `${dk64Colors.dk} Lava GB [135]. Leave Lobby. Fall to Japes Entry GB [136]`,
    `${dk64Colors.lanky} Instrument GB [137]`,
    `${dk64Colors.dk} Enter Japes`,
    `${dk64Colors.header} *Japes`,
    `${dk64Colors.dk} Bush Push.`,
    `${dk64Colors.diddy} Tag Anywhere Skew over DK Caged.`,
    `${dk64Colors.dk} Caged GB [138]. W3 bunch  and Balloon (15). Blueprint.`,
    `${dk64Colors.tiny} Blueprint. Stump GB [139], Logs (30). Skew through red wall.`,
    `${dk64Colors.chunky} Caged GB [140]. Backflip onto Funky's Hut then to Snide's area.`,
    `${dk64Colors.chunky} Caged GB [141]`,
    `${dk64Colors.dk} Snide's Balloon (25). Tag W2. To Diddy Cage (31) [142, 143].`,
    `${dk64Colors.tiny} PTT to Cannon Tree`,
    `${dk64Colors.dk} Cannon Tree (36).`,
    `${dk64Colors.lanky} Caged GB [144]`,
    `${dk64Colors.tiny} Caged GB [145]`,
    `${dk64Colors.dk} W3 bunch (41).`,
    `${dk64Colors.diddy} Blueprint (3). Skew to Fairy.`,
    `${dk64Colors.tiny} Fairy and balloon (40). Singles (44).`,
    `${dk64Colors.chunky} Balloons (30).`,
    `${dk64Colors.tiny} Singles out (47). Cranky Balloon (57).`,
    `${dk64Colors.lanky} Cranky Balloon (10).`,
    `${dk64Colors.dk} Cranky Balloon (51). Singles to Lanky Area (56).`,
    `${dk64Colors.lanky} Blueprint, Balloon, Speedy Swing Sortie (24) [146].`,
    `${dk64Colors.dk} Singles back to main area (60). Phase Swim to Underground.`,
    `${dk64Colors.chunky} Underground for CBs, Blueprint, and GB (45) [147]. Rock GB. [148].`,
    `${dk64Colors.dk} Bblast (70) [149].`,
    `${dk64Colors.chunky} Phase Fall/Walk/Swim to Tunnel. Key 1.`,
    `${dk64Colors.tiny} Splish Splash Salvage (62) [150].`,
    `${dk64Colors.lanky} Open Gate.`,
    `${dk64Colors.diddy} Balloon and GB (13) [151]. Enter Mad Maze Maul.`,
    `${dk64Colors.lanky} Bonus GB (29) [152]. Back to main area however you wish.`,
    `${dk64Colors.dk} Climb to Funky for Crown. Funky Tree (75).`,
    `${dk64Colors.chunky} Funky Bunches (55)`,
    `${dk64Colors.lanky} Snide's Bunch and Tree (39).`,
    `${dk64Colors.lanky} Oh Banana [160]`,
    `${dk64Colors.tiny} Oh Banana [168]`,
    `${dk64Colors.chunky} Oh Banana [176]`,
    `${dk64Colors.dk} Oh Banana [184]`,
    `${dk64Colors.diddy} Oh Banana [192]`,
    `${dk64Colors.diddy} Shoot Mountain Switch. Enter Mountain (16). Slam Switch. Water, Balloon, enter Minecart (41) [193].`,
    `${dk64Colors.diddy} Open Painting Room.`,
    `${dk64Colors.lanky} Painting Room GB and Fairy (72) [194].`,
    `${dk64Colors.diddy} Trees for Bunches (51). Underwater Bunches (61).`,
    `${dk64Colors.lanky} Underwater Bananas (75). Surface and take W2 up.`,
    `${dk64Colors.diddy} Shoot Mountain switch again and get the other singles (65). GB and Balloon on top (75) [195]. W5.`,
    `${dk64Colors.chunky} Hunky Chunky into Minecart Mayhem. Fast Speed: Stay 2, Switch 9, Stay 1, Switch 2`,
    `${dk64Colors.chunky} Hunky for CBs and GB (75) [196]. Detransform at entrance to hive to break in.`,
    `${dk64Colors.tiny} Balloon in first room (72). OOB to final room. Singles for (75) and GB [197]. Pause Exit.`,
    `${dk64Colors.header} *Japes to End`,
    `${dk64Colors.dk} Green Island Fairy. STS under BFI.`,
    `${dk64Colors.tiny} Caged GB [198]. Enter BFI. Rareware GB [199]. Leave BFI.`,
    `${dk64Colors.chunky} Go to Green Island again. Hunky Chunky. Pound X, STS for Caged [200], X GB [201] back to K. Rool.`,
    `${dk64Colors.header} *ALTERNATE ROUTES`,
    `${dk64Colors.header} *Fungi without Rabbit Race Skip`,
    `${dk64Colors.dk} Red Tunnel (5). Phase swim through wall on Cranky side of Giant Mushroom.`,
    `${dk64Colors.lanky} Tag Mushroom W3 (5). CBs around right side (8). Swim underneath Wood Tunnel to Giant Tree Area. Tag Anywhere Skew at end of tunnel.`,
    `${dk64Colors.diddy} Backflip inbounds. Tag W4 (5).`,
    `${dk64Colors.lanky} Blueprint.`,
    `${dk64Colors.tiny} Skew OOB and backflip into Anthill. DO NOT EARLY GRAB THE GB.`,
    `${dk64Colors.tiny} Instrument for GB and Bean [3], cannon out. Backflip Slope Reset standing combo to get on top of the anthill for the bunch (5).`,
    `${dk64Colors.lanky} Start Rabbit Race Round 1 (13).`,
    `${dk64Colors.dk} Rabbit Race Round 1. (Tag Anywhere to DK for the majority of the race).`,
    `${dk64Colors.tiny} Tag Anywhere to Tiny and grab all the CBs around Anthill during the race (13).`,
    `${dk64Colors.lanky} Rabbit Race Round 2 (you can skip the Lanky singles) [4]. Use Orangstand Sprint Barrel.`,
    `${dk64Colors.lanky} Exit/Enter on GB.`,
    `${dk64Colors.chunky} W2 (5)`,
    `${dk64Colors.lanky} W1 (18)`,
    `${dk64Colors.diddy} Rocketbarrel to clock turn to night (15). Take W4 (20). 5 CBs around left of Tree (25). Summon Owl. 3 CBs to Rocketbarrel (28). Owl Race (33) [5]. Fall to last 2 CBs and take W4 back (35).`,
    `${dk64Colors.chunky} Well (10) [6].`,
    `${dk64Colors.tiny} Swim CW for 7 (20). Phase Swim under Mill.`,
    `${dk64Colors.diddy} Tag Anywhere Skew for Underwater Caged [7]. Backflip inbounds.`,
    `${dk64Colors.tiny} Skew into Tiny entrance (25)`,
    `${dk64Colors.chunky} Start Crusher (15)`,
    `${dk64Colors.tiny} Spider [8] and back mill CBs (40)`,
    `${dk64Colors.chunky} OOB to front of mill. Mill GB [9]. Crusher GB [10]. Flicker Walk OOB near Lanky Coins.`,
    `${dk64Colors.dk} Balloon (15). Leave Mill.`,
    `${dk64Colors.lanky} Baboon Balloon to Attic (28) [11]. 2 CBs on roof (30).`,
    `${dk64Colors.dk} Zoom out camera and Moonkick to mushroom by Blue Tunnel.`,
    `${dk64Colors.diddy} Snipe Snide's balloon (45).`,
    `${dk64Colors.dk} Balloon behind Diddy barn (25)`,
    `${dk64Colors.diddy} Diddy Attic [12] (63) and Fairy. Leave Diddy Attic.`,
    `${dk64Colors.tiny} Swim to thorn bushes for 5 (45). Phase Swim and Skew on thorn bushes.`,
    `${dk64Colors.tiny} Balloon (55). Inbounds near Funky.`,
    `${dk64Colors.chunky} Tag W2 (20). Hunky Chunky for Apple and CBs [13] (29). Skew through blue wall.`,
    `${dk64Colors.dk} Blueprint. Bunch over switch (30). Enter DK Barn. Minecart Mayhem and Fairy [14] (35).`,
    `${dk64Colors.header} Fungi Minecart Mayhem:`,
    `${dk64Colors.header} 3-2-1-1-4-2-go back to inside track`,
    `${dk64Colors.dk} Exit/Enter on Fairy.`,
    `${dk64Colors.tiny} Take W3 (60).`,
    `${dk64Colors.chunky} Bananas around left (35).`,
    `${dk64Colors.diddy} Rocketbarrel to Teetering Turtle Trouble [15] (73)`,
    `${dk64Colors.lanky} Switch (40), Dark Room (bottom right lanky face) [16] (50)`,
    `${dk64Colors.lanky} Switch, Light Room (upper left lanky face) [17] (55)`,
    `${dk64Colors.diddy} CBs to Crown (75). Crown. Climb back up.`,
    `${dk64Colors.chunky} Face Puzzle and balloon [18] (44) Blueprint and balloon (54). Enter Mush (59). Drop left.`,
    `${dk64Colors.diddy} Blueprint.`,
    `${dk64Colors.chunky} Drop for CBs (75)`,
    `${dk64Colors.chunky} Shoot Switch.`,
    `${dk64Colors.dk} Shoot Switch.`,
    `${dk64Colors.diddy} Shoot Switch.`,
    `${dk64Colors.lanky} Shoot Switch and Balloon (65)`,
    `${dk64Colors.tiny} Shoot Switch and Slam Switch Overlap (65) and Speedy Swing Sortie. [19]`,
    `${dk64Colors.dk} Slam Switch and take Cannons to GB [20] (50)`,
    `${dk64Colors.lanky} Balloon (75)`,
    `${dk64Colors.dk} Leave Mush. W5 bunch (55). Drop left of W5 to Bblast GET COINS [21] (65). CBs around left to Tiny Kasplat (75)`,
    `${dk64Colors.tiny} Blueprint and balloon (75). Drop into water and Tag Anywhere Skew. Backflip inbounds and skew through wall by tag barrel to Beanstalk. Mini Monkey, Plant Bean, Instrument [22]. Pause Exit.`,
    `${dk64Colors.header} *Helm Backup strat if you don't believe you'll finish Diddy Room in time`,
    `${dk64Colors.lanky} Quit Game after completing Lanky's Medal`,
    `${dk64Colors.dk} Re-enter Helm and get back to BoM room`,
    `${dk64Colors.diddy} Rocketbarrel up to Diddy's Room and Double Phasewalk in`,
    `${dk64Colors.diddy} After getting Diddy's Medal, Crystal Push out and complete Helm as normal`
  ]
};
